### ISSUE TITLE
ios  Compile error :  Unable to resolve module http

### ISSUE THREAD

**Issue by 420chen** [buhe/react-native-app-qiufit#2]
There is a wrong with ios :

uncaught error Error: UnableToResolveError: Unable to resolve module http from /Users/chen420/Documents/ios/react-native-app-qiufit/node_modules/avoscloud-sdk/dist/node/browserify-wrapper/ajax.js: Invalid directory /Users/node_modules/http

**Comment by buhe** [comment]
谢谢反馈，我去看看

**Comment by buhe** [comment]
https://github.com/leancloud/javascript-sdk/commit/da6b457c67570c37d3d86306f266ea53b7c7c26e

我了解了leancloud的实现方式，他们最近做了个改动，请把package改成和他们一致再试一下。 或者直接引用他们github上面的版本

我本地居然不出错也是神奇。。

**Comment by buhe** [comment]
我估计这个就是 问题的原因

**Comment by 420chen** [comment]
改了之后 可以看到页面了

**Comment by buhe** [comment]
那我关闭了? @420chen

**Comment by 420chen** [comment]
稍等 还有其它问题

**Comment by 420chen** [comment]
刚才几秒钟会自动出错 并且每个页面都是这样

后面：
1、我又重新下载安装
2、将包文件替换了 

现在一切都正常了  
可以关闭了
